build_from:
  aarch64: ghcr.io/hassio-addons/base:13.0.0
  amd64: ghcr.io/hassio-addons/base:13.0.0
  armhf: ghcr.io/hassio-addons/base:13.0.0
  armv7: ghcr.io/hassio-addons/base:13.0.0
  i386: ghcr.io/hassio-addons/base:13.0.0
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
args:
  N8N_VERSION: "0.211.0"