---
name: N8N
version: dev
slug: n8n
description: N8N add-on by Community Home Assistant Add-ons
url: https://github.com/pedrol3001/addon-n8n
codenotary: contact@pedrol.me
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: mdi:sitemap
ports:
  80/tcp: 5678
ports_description:
  80/tcp: Web Interface
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
auth_api: true
map:
  - config:rw
  - ssl
options:
  log_level: info
  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  db_type: sqlite
schema:
  log_level: list(info|warn|error|verbose|debug)
  ssl: bool
  certfile: str
  keyfile: str
  db_type: list(sqlite|postgresdb|mysqldb)
  db_name: str?
  db_host: url?
  db_port: port?
  db_user: str?
  db_password: str?
  public_url: str?
 