---
name: N8N
version: dev
slug: n8n
description: N8N add-on by Community Home Assistant Add-ons
url: https://github.com/pedrol3001/addon-n8n
codenotary: contact@pedrol.me
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_level: info
panel_icon: mdi:sitemap
ports:
  80/tcp: 5678
ports_description:
  80/tcp: Web interface
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
