# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: n8n addon
version: "0.0.2"
slug: n8n
description: Add a n8n server to home assistant
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
host_pid: true
ports:
  80/tcp: 5678
ports_description:
  80/tcp: Web interface
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
image: ghcr.io/pedrol3001/image-{arch}-addon-n8n